language: python

python:
  - "2.6"
  - "2.7"
install:
  - pip install coveralls # For coveralls.io specifically
  - pip install -r tests_requirements.txt
script:
  - python tests/test_loggers.py 
after_success:
- coveralls
