language: python

python:
  - "2.7"
install:
  - pip install -e .
  - pip install coveralls # For coveralls.io specifically
  - pip install -r tests_requirements.txt
script:
  #- python tests/test_loggers.py
    # Main tests, w/ coverage!
  #- inv tests/test_loggers.py --coverage
  - inv test --coverage
after_success:
- coveralls
